config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  get 'tasks/search'
  resources :tasks
  get 'sessions/index'
  get 'sessions/new'

  resources :users, only: [:new, :create, :edit, :update, :destroy]

 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  def self.search(keyword)
    #タスクのタイトルと詳細で検索
    where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper





  private
   # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    # @tasks = Task.all
    @tasks = Task.order("#{sort_column} #{sort_direction}")
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : 'importance'
  end

  def new
    @tasks = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url
  end

  def search
    @tasks = Task.search(params[:keyword])
    @tasks = @tasks.all
    @keyword = params[:keyword]
    render "index"
  end
  
  #ストロングパラメーター
  private
    def task_params
      params.require(:task).permit(:title, :body, :importance)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @users = User.new
  end

  def create
    @users = User.create(user_params)

    redirect_to root_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
  private
　#ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
     #@current_user = @current_user || User.find_by(id: session[:user_id])と同じ意味
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
  user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sort_order(column, importance, hash_param = {})
   css_class = column == sort_column ? "current #{sort_direction}" : nil
   direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
   link_to importance, { sort: column, direction: direction }.merge(hash_param), class: "sort_header #{css_class}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
 <div class="container">
  <div class = "row ">
    <div class="col-1 h1 mt-1" href="/">
      <%= link_to  root_path, class: "homelink" do %>
        <%= image_tag asset_path("icon1.jpeg"), class: 'headerimage' %>
      <% end %>
    </div>
     <div class="col mt-1" >
     　<h1>TODO List</h1>
    </div>
  </div>


　<%= form_with url: tasks_search_path, method: :get, local: true do |f| %>
  <div class="row justify-content-end ">
    <div class="col-3 my-3">
      <%= f.text_field :keyword, value: @keyword, class:"form-control" %>
    </div>
    <div class="col-1 my-3">
      <%= f.submit "検索", class:"btn btn-success flex-shrink-0" %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pf4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
    <footer class=" p-5">

    </footer>
  </body>
</html>

app/views/tasks/_logged_in.html.erb
<table class="table table-success table-bordered table-hover">
    <thead class="table-light">
      <tr>
        <th><%= sort_order "title", "タスク名" %></th>
        <th><%= sort_order "body", "タスク内容" %></th>
        <th><%= sort_order "importance", "重要度" %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>

        <tr>

            <td><%= task.title %></td>
            <td><%= task.body %></td>
            <td><%= task.importance %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "完了", task_path(task), method: :delete %></td>

        </tr>

      <% end %>
    </tbody>
</table>
<%= link_to "タスク追加", new_task_path, class:"btn btn-success flex-shrink-0" %>
<%= link_to "ログアウト", logout_path, method: :delete, class:"btn btn-danger flex-shrink-0" %>

app/views/tasks/_not_logged_in.html.erb
<div class = "container mx-auto m-5">
  <p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
  <%= link_to "ログイン", login_path, class: "btn btn-outline-primary rounded-pill" %>
  <%= link_to "新規登録", new_user_path, class: "btn btn-outline-primary rounded-pill" %>
</div>

app/views/tasks/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-12 col-lg-10 offset-lg-1 ">



      <div class="row mx-auto">
        <div class="col">
          <h2 class="fas fa-wrench m-5 rounded p-3 border border-secondary">タスク編集</h2>
        </div>
      </div>
      <%= form_for(@task) do |f| %>

        <div class="row mb-3">
          <%= f.label :タスク名, class:"col-3 col-form-label" %>

          <div class="col-12 col-lg-8">
            <%= f.text_field :title, class:"form-control" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :タスク内容, class:"col-3 col-form-label" %>
          <div class="col-12 col-lg-8">
            <%= f.text_field :body, autofocus: true, class:"form-control" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :重要度, class:"col-3 col-form-label" %>
          <div class="col-12 col-lg-8">
            <%= f.text_field :importance, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>
        </div>

        <div class="row m-5">
          <div class="col-3">
          </div>
          <div class="col-6">
          　<%= f.submit "            編集内容を保存           ", class:"btn btn-success" %>
          </div>
        </div>
      <% end %>
      <div><%= link_to '戻る', tasks_path, class:"btn btn-success" %></div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class = "container mx-auto m-5">


  <h1>タスク一覧</h1>
  <% if logged_in? %>
    <%= render 'tasks/logged_in' %>
  <% else %>
    <%= render 'tasks/not_logged_in' %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-12 col-lg-10 offset-lg-1 ">



      <div class="row mx-auto">
        <div class="col">
          <h2 class="fas fa-wrench m-5 rounded p-3 border border-secondary">タスク登録</h2>
        </div>
      </div>
      <%= form_for(@tasks) do |f| %>

        <div class="row mb-3">
          <%= f.label :タスク名, class:"col-3 col-form-label" %>

          <div class="col-12 col-lg-8">
            <%= f.text_field :title, class:"form-control" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :タスク内容, class:"col-3 col-form-label" %>
          <div class="col-12 col-lg-8">
            <%= f.text_field :body, autofocus: true, class:"form-control" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :重要度, class:"col-3 col-form-label" %>
          <div class="col-12 col-lg-8">
            <%= f.text_field :importance, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>
        </div>

        <div class="row m-5">
          <div class="col-3">
          </div>
          <div class="col-6">
          　<%= f.submit "            編集内容を保存           ", class:"btn btn-success" %>
          </div>
        </div>
      <% end %>
      <div><%= link_to '戻る', tasks_path, class:"btn btn-success" %></div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container pl-5 mb-5">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-12 col-lg-6 border border-top-0 mt-5">
      <h1 class="fas fa-user-plus">新規登録</h1>
      <%= form_for(@users) do |f| %>

      　<div class="field">
          <%= f.label :名前, class: "form-label" %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "名前" %>
        </div>

        <div class="field">
          <%= f.label :メールアドレス, class: "form-label" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "メールアドレス" %>
        </div>



        <div class="field">
          <%= f.label :パスワード, class: "form-label" %>

          <%= f.password_field :password, autocomplete: "new-password", class: "form-control", placeholder: "パスワード" %>
        </div>

        <div class="field">
          <%= f.label :"パスワード (確認)", class: "form-label" %>

          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder: "パスワード" %>
        </div>


        <div class="row justify-content-end">
          <div class="col-3">
            <%= f.submit "Sign up", class: "btn btn-outline-success rounded-pill" %>
          </div>
        </div>
      <% end %>


    </div>
  </div>
</div>